install_shop_with_modules:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}",
              "oxid-professional-services/countryvatadministration": "{{ .Data.global.composer.ref_name }}"
          },
          "repositories": {
            "oxid-professional-services/countryvatadministration": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/country-vat-module.git"
            }
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:database:reset --db-host=mysql --db-port=3306 --db-name=example --db-user=root --db-password=root --force
    vendor/bin/oe-console oe:module:activate oecountryvat
    vendor/bin/oe-console oe:theme:activate apex

runscript: &runscript
  matrix:
    script: |
      [
        "country_vat:tests-integration",
        "country_vat:tests-codeception"
      ]
  country_vat:
    path: 'vendor/oxid-professional-services/countryvatadministration'

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "country_vat:phpcs",
        "country_vat:phpstan",
        "country_vat:phpmd"
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/vendor/oxid-professional-services/countryvatadministration/'
  project_key: 'OXID-eSales_country-vat-module'
  project_name: 'oxid-professional-services/countryvatadministration'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests
    -Dsonar.php.phpstan.reportPaths=coverage-reports/phpstan.report.json

finish:
  slack_title: 'Country vat module ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
